image: docker:latest

services:
 - docker:dind

build:
  script:
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" $CI_REGISTRY
    - sed -i "s/REPLACE_REGISTRY/$CI_REGISTRY/g" Dockerfile 
    - docker build -t $CI_REGISTRY_IMAGE --pull  . 
    - docker push $CI_REGISTRY_IMAGE

